"""rename department

Revision ID: 31b2f3eb0a49
Revises: 71c7e10c9e24
Create Date: 2025-02-04 20:23:07.990847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b2f3eb0a49'
down_revision = '71c7e10c9e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
